# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          python sample.py
      - name: Notify on Build Failure
        if: ${{ failure() }}
        run: |
          echo "Build Failed"
          
      - name: Notify on Build Success
        if: ${{ success() }}
        run: |
          echo "Build Successful"
          echo "Sending email notification..."
          echo "Subject: Build Successful" | send-email -to ${{ secrets.EMAIL_ADDRESS }} -s smtp.example.com -f your_email@example.com -xu your_email@example.com -xp ${{ secrets.SMTP_PASSWORD }}

          

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          python sample.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Deploy
        run: |
          python ./sample.py  # Use ./ to explicitly specify the path
      - name: Notify on Deployment Failure
        if: ${{ failure() }}
        run: |
          echo "Deployment Failed"
          echo "Subject: Deployment Failed" | send-email -to ${{ secrets.EMAIL_ADDRESS }} -s smtp.example.com -f your_email@example.com -xu your_email@example.com -xp ${{ secrets.SMTP_PASSWORD }}
          exit 1  # This will mark the job as failed
